image: registry.gitlab.com/passbolt/passbolt-ci-docker-images/golang-1.15

default:
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - api_failure
      - stale_schedule

stages:
  - Run go tests

Run unit tests:
  stage: Run go tests
  script:
    - go test -cover ./...
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "schedule"'
