image: registry.gitlab.com/passbolt/passbolt-ci-docker-images/android-gopenpgp:latest

default:
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - api_failure
      - stale_schedule

stages:
  - Test
  - Build

Run unit tests:
  stage: Test
  script:
    - go test -cover ./...
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

Build gopenpgp library:
  stage: Build
  script:
    - gomobile init
    - sh build.sh android
  artifacts:
    paths:
      - dist/android
    expire_in: 1 year
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
