image: $CI_REGISTRY_IMAGE/android-gopenpgp:latest

default:
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - api_failure
      - stale_schedule

stages:
  - Build image
  - Test
  - Build

Build docker image:
  stage: Build image
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - >
      /kaniko/executor --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $CI_REGISTRY_IMAGE/android-gopenpgp:latest
  rules:
    - changes:
        - Dockerfile
      when: always

Run unit tests:
  stage: Test
  script:
    - go test -cover ./...
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

Build gopenpgp library:
  stage: Build
  script:
    - gomobile init
    - sh build.sh android
  artifacts:
    paths:
      - dist/android
    expire_in: 1 year
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
